export const users = [
  {
    id: 1,
    first_name: 'Marmaduke',
    last_name: 'Gatchel',
    email: 'mgatchel0@twitpic.com',
    gender: 'Genderfluid',
    phone_number: '838-385-1308',
  },
  {
    id: 2,
    first_name: 'Alvinia',
    last_name: 'Truckell',
    email: 'atruckell1@theguardian.com',
    gender: 'Female',
    phone_number: '639-294-3181',
  },
  {
    id: 3,
    first_name: 'Elsinore',
    last_name: 'Haddington',
    email: 'ehaddington2@paypal.com',
    gender: 'Female',
    phone_number: '334-226-5608',
  },
  {
    id: 4,
    first_name: 'Burch',
    last_name: 'Craster',
    email: 'bcraster3@twitpic.com',
    gender: 'Male',
    phone_number: '978-651-7088',
  },
  {
    id: 5,
    first_name: 'Lilas',
    last_name: 'Watling',
    email: 'lwatling4@amazon.co.jp',
    gender: 'Female',
    phone_number: '784-822-9773',
  },
  {
    id: 6,
    first_name: 'Brooke',
    last_name: 'Shallow',
    email: 'bshallow5@indiegogo.com',
    gender: 'Female',
    phone_number: '441-240-9841',
  },
  {
    id: 7,
    first_name: 'Margarette',
    last_name: 'Blaase',
    email: 'mblaase6@cornell.edu',
    gender: 'Female',
    phone_number: '406-539-7648',
  },
  {
    id: 8,
    first_name: 'Saraann',
    last_name: 'Pierucci',
    email: 'spierucci7@wufoo.com',
    gender: 'Genderqueer',
    phone_number: '648-827-4931',
  },
  {
    id: 9,
    first_name: 'Judah',
    last_name: 'Rampage',
    email: 'jrampage8@chronoengine.com',
    gender: 'Male',
    phone_number: '999-325-0230',
  },
  {
    id: 10,
    first_name: 'Jerrie',
    last_name: 'Sciacovelli',
    email: 'jsciacovelli9@indiegogo.com',
    gender: 'Female',
    phone_number: '891-195-9529',
  },
  {
    id: 11,
    first_name: 'Andrus',
    last_name: 'Betty',
    email: 'abettya@buzzfeed.com',
    gender: 'Male',
    phone_number: '572-854-3755',
  },
  {
    id: 12,
    first_name: 'Viviyan',
    last_name: 'McCarry',
    email: 'vmccarryb@nature.com',
    gender: 'Female',
    phone_number: '314-740-4848',
  },
  {
    id: 13,
    first_name: 'Prince',
    last_name: 'Hedley',
    email: 'phedleyc@friendfeed.com',
    gender: 'Male',
    phone_number: '177-355-2743',
  },
  {
    id: 14,
    first_name: 'Sampson',
    last_name: 'Hamby',
    email: 'shambyd@cloudflare.com',
    gender: 'Male',
    phone_number: '713-932-0246',
  },
  {
    id: 15,
    first_name: 'Fernanda',
    last_name: 'Alti',
    email: 'faltie@biglobe.ne.jp',
    gender: 'Female',
    phone_number: '936-154-6188',
  },
  {
    id: 16,
    first_name: 'Bink',
    last_name: 'Giacobazzi',
    email: 'bgiacobazzif@cbslocal.com',
    gender: 'Male',
    phone_number: '727-744-6442',
  },
  {
    id: 17,
    first_name: 'Leif',
    last_name: 'Martinat',
    email: 'lmartinatg@cam.ac.uk',
    gender: 'Male',
    phone_number: '483-644-3625',
  },
  {
    id: 18,
    first_name: 'Ronni',
    last_name: 'Illyes',
    email: 'rillyesh@theguardian.com',
    gender: 'Female',
    phone_number: '362-575-1148',
  },
  {
    id: 19,
    first_name: 'Parke',
    last_name: 'Louth',
    email: 'plouthi@jugem.jp',
    gender: 'Male',
    phone_number: '168-105-1937',
  },
  {
    id: 20,
    first_name: 'Jackelyn',
    last_name: 'Brimelow',
    email: 'jbrimelowj@mtv.com',
    gender: 'Female',
    phone_number: '982-883-9872',
  },
];
